# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11b3782a30b6ac1e7706acb9bfb1ef08d36632a33768ead9a916ec79db950f0fc79a032cfa1475cedcd8f45453e8ac3ef29f6f8b9b616c9f2256103cbf3f4868

test:
  secret_key_base: bebab22894e8a2b170b45c6ee0ad130f43b22bf351aae427f5091ee49e651862bc47ce0579cf46e840e8d2f848bdf6e2137fe03241edc901db649602d2cddea9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
